#!/bin/bash
#
# Description : Ubuntu update script for Croissants
#
# Author      : Samiux
# Website     : https://samiux.github.io
# Blog        : http://samiux.blogspot.com
# Date        : OCT 09, 2022
# Version     : 0.6
# License     : GPLv3 (Open Source)

# colour code
GREEN='\033[0;32m'
RED='\033[0;31m'
RESET='\033[0m'

# get the input
INPUT=$0
# get the string after "_"
SUBSTRING=$(echo $INPUT | cut -d '_' -f 2)
# uppercase the first character
OUTPUT=$(echo "${SUBSTRING^}")

# update ubuntu
echo ""
echo -e "${GREEN}Updating $OUTPUT ...${RESET}"
export DEBIAN_FRONTEND=noninteractive
sudo apt update
sudo DEBIAN_FRONTEND=noninteractive apt -o="APT::Get::Always-Include-Phased-Updates=true" -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -o APT::Get::Assume-Yes="true" -y full-upgrade --allow-downgrades
sudo apt -y autoclean
sudo apt -y --purge autoremove

# triming SSD if any
echo ""
echo -e "${GREEN}Triming SSD ...${RESET}"
sudo fstrim -av

# check if reboot is required
echo ""

if [ -f /var/run/reboot-required ]
then
        echo -e "${RED}$OUTPUT is updated.  Reboot is required!${RESET}"
        sudo reboot
else
        echo -e "${GREEN}$OUTPUT is updated!${RESET}"
fi

echo ""

# EOF

