#!/bin/bash
# Author   : Samiux (https://samiux.github.io)
# Date     : SEP 06, 2020
# License  : GPLv3 (Open Source)

# get variables from nsm.conf
. /etc/croissants/conf.d/nsm.conf

# check the connectivity
sleep 10
RESULT_0=$(fping -r 1 google.com)
sleep 10
RESULT_1=$(fping -r 1 baidu.com)

echo "$RESULT_0"
echo "$RESULT_1"

if [[ $RESULT_0 == *"alive"* ]] || [[ $RESULT_1 == *"alive"* ]]
then
        # can ping
        echo "Host google.com or github.com alives"
        # get the current external IP address
        #CUR_EXT_IP=$(dig +short myip.opendns.com @resolver1.opendns.com)
        CUR_EXT_IP=$(curl -s http://whatismijnip.nl |cut -d " " -f 5)
        echo "The current IP is $CUR_EXT_IP"
        echo "The external IP is $EXT_IP"
        if [[ "$CUR_EXT_IP" != "" ]]; then
                # main routine
                # external ip doesn't match
                OCTETS_EXT_IP=$(awk -F. -v OFS=. '{print $1, $2}' <<< $EXT_IP)
                OCTETS_CUR_EXT_IP=$(awk -F. -v OFS=. '{print $1, $2}' <<< $CUR_EXT_IP)
                #if [[ "$EXT_IP" != "$CUR_EXT_IP" ]]; then
                if [[ "$OCTETS_EXT_IP" != "$OCTETS_CUR_EXT_IP" ]]; then
                        echo "Croissants external IP address NOT match!  Resetting external IP address ...."
                        echo $(date) " " "$EXT_IP" | sudo tee --append /etc/croissants/conf.d/old_ip.txt
                        sudo sed -i 's/EXT_IP=.*/EXT_IP=\"'$OCTETS_CUR_EXT_IP\.0\.0\/16'\"/g' /etc/croissants/conf.d/nsm.conf
                        sudo /etc/croissants/conf.d/set_timezone
                        sudo /etc/croissants/conf.d/auto_config
                else
                        echo "Current and external IP addresses are matched!"
                fi
        fi
else
        # cannot ping
        echo "Hosts google.com and baidu.com is unreachable or not exists!  Resetting network interfaces ..."
        sudo /etc/croissants/conf.d/resetfirewall
fi
